- hosts: all
  gather_facts: true
  become: true
  roles:
    - docker
    - network
    - database
    - app
    - front
    - proxy
    - role: cloudalchemy.grafana
      vars:
        grafana_security:
          admin_user: admin
          admin_password: TeSt54321#