- name: copy env file
  ansible.builtin.copy:
    src: .env
    dest: .

- name: Run database
  docker_container:
    name: db
    image: qwertyjuju/pgsql-simple-api:latest
    networks:
      - name: http
      - name: backend 