- name: Run HTTPD
  docker_container:
    name: httpd
    image: qwertyjuju/http-simple-api:latest
    pull: yes
    published_ports: 
      - 80:80
      - 8080:8080
    networks:
      - name: http
