name: Push docker and deploy 
on: 
  workflow_run:
    workflows: 
      - build-push-all
    types:
      - completed
    branches:
      - master
jobs:
  run-ansible-playbook:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
        packages: write
        contents: read
        attestations: write
        id-token: write
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: webfactory/ssh-agent@v0.9.0
        with: 
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Ajouter l'env
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ENV }}" > tp3/project/ansible/roles/database/tasks/.env
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Installer Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Exécuter le Playbook Ansible
        run: |
          ansible-playbook -i tp3/project/ansible/inventories/setup.yml tp3/project/ansible/playbook.yml