name: test-frontend-devops
on:
    push:
        branches: 
            - develop
            - master 

jobs:
  test-frontend: 
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: install yarn
        run: npm install --global yarn
      - name: config yarn
        uses: borales/actions-yarn@v4
        with:
          cmd: yarn config set strict-ssl false
          dir: tp3/project/front
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
          dir: tp3/project/front
      - name: Build production bundle
        uses: borales/actions-yarn@v4
        with:
            cmd: build:prod
            dir: tp3/project/front
      - name: Test the app
        uses: borales/actions-yarn@v4
        with:
            cmd: test
            dir: tp3/project/front