name: test-frontend-devops
on:
    push:
        branches: 
            - develop
            - master 

jobs:
  test-backend: 
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
          dir: tp3/project/front
      - name: Build production bundle
        uses: borales/actions-yarn@v4
        with:
            cmd: build:prod
            dir: tp3/project/front
      - name: Test the app
        uses: borales/actions-yarn@v4
        with:
            cmd: test
            dir: tp3/project/front